services:
  web:
    image: php:7.4-apache

    ports:
      - "8000:80"

    volumes:
      - .:/var/www/html

    working_dir: /var/www/html

    command: >
      bash -c "
        docker-php-ext-install mysqli &&
        apache2-foreground
      "

    restart: unless-stopped

  db:
    image: mysql:5.7.33

    environment:
      MYSQL_DATABASE: ScorecardV5
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
      MYSQL_ROOT_PASSWORD: passw0rd

    volumes:
      - ./includes:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql

    restart: unless-stopped
